// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: assignments.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (
    draw_id, gifter_member_id, giftee_member_id, gifter_phone_number, giftee_phone_number
) VALUES (?, ?, ?, ?, ?) RETURNING id, draw_id, gifter_member_id, giftee_member_id, gifter_phone_number, giftee_phone_number, created_at
`

type CreateAssignmentParams struct {
	DrawID            int64         `json:"draw_id"`
	GifterMemberID    sql.NullInt64 `json:"gifter_member_id"`
	GifteeMemberID    sql.NullInt64 `json:"giftee_member_id"`
	GifterPhoneNumber string        `json:"gifter_phone_number"`
	GifteePhoneNumber string        `json:"giftee_phone_number"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, createAssignment,
		arg.DrawID,
		arg.GifterMemberID,
		arg.GifteeMemberID,
		arg.GifterPhoneNumber,
		arg.GifteePhoneNumber,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.DrawID,
		&i.GifterMemberID,
		&i.GifteeMemberID,
		&i.GifterPhoneNumber,
		&i.GifteePhoneNumber,
		&i.CreatedAt,
	)
	return i, err
}

const listAssignmentsByDraw = `-- name: ListAssignmentsByDraw :many
SELECT id, draw_id, gifter_member_id, giftee_member_id, gifter_phone_number, giftee_phone_number, created_at FROM assignments WHERE draw_id = ? ORDER BY id
`

func (q *Queries) ListAssignmentsByDraw(ctx context.Context, drawID int64) ([]Assignment, error) {
	rows, err := q.db.QueryContext(ctx, listAssignmentsByDraw, drawID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assignment
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.DrawID,
			&i.GifterMemberID,
			&i.GifteeMemberID,
			&i.GifterPhoneNumber,
			&i.GifteePhoneNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
