// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: drawers.sql

package sqlc

import (
	"context"
)

const createDrawer = `-- name: CreateDrawer :one
INSERT INTO drawers (name, organiser_kratos_identity_id) VALUES (?, ?) RETURNING id, name, organiser_kratos_identity_id, created_at, updated_at
`

type CreateDrawerParams struct {
	Name                      string `json:"name"`
	OrganiserKratosIdentityID string `json:"organiser_kratos_identity_id"`
}

func (q *Queries) CreateDrawer(ctx context.Context, arg CreateDrawerParams) (Drawer, error) {
	row := q.db.QueryRowContext(ctx, createDrawer, arg.Name, arg.OrganiserKratosIdentityID)
	var i Drawer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganiserKratosIdentityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDrawer = `-- name: DeleteDrawer :exec
DELETE FROM drawers WHERE id = ?
`

func (q *Queries) DeleteDrawer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDrawer, id)
	return err
}

const getDrawer = `-- name: GetDrawer :one
SELECT id, name, organiser_kratos_identity_id, created_at, updated_at FROM drawers WHERE id = ?
`

func (q *Queries) GetDrawer(ctx context.Context, id int64) (Drawer, error) {
	row := q.db.QueryRowContext(ctx, getDrawer, id)
	var i Drawer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganiserKratosIdentityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDrawersByOrganiser = `-- name: ListDrawersByOrganiser :many
SELECT id, name, organiser_kratos_identity_id, created_at, updated_at FROM drawers WHERE organiser_kratos_identity_id = ? ORDER BY id
`

func (q *Queries) ListDrawersByOrganiser(ctx context.Context, organiserKratosIdentityID string) ([]Drawer, error) {
	rows, err := q.db.QueryContext(ctx, listDrawersByOrganiser, organiserKratosIdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Drawer
	for rows.Next() {
		var i Drawer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrganiserKratosIdentityID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDrawer = `-- name: UpdateDrawer :one
UPDATE drawers SET name = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, organiser_kratos_identity_id, created_at, updated_at
`

type UpdateDrawerParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateDrawer(ctx context.Context, arg UpdateDrawerParams) (Drawer, error) {
	row := q.db.QueryRowContext(ctx, updateDrawer, arg.Name, arg.ID)
	var i Drawer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganiserKratosIdentityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
