// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: draws.sql

package sqlc

import (
	"context"
	"time"
)

const createDraw = `-- name: CreateDraw :one
INSERT INTO draws (drawer_id, exchange_date, budget_amount) VALUES (?, ?, ?) RETURNING id, drawer_id, exchange_date, budget_amount, status, created_at, updated_at
`

type CreateDrawParams struct {
	DrawerID     int64     `json:"drawer_id"`
	ExchangeDate time.Time `json:"exchange_date"`
	BudgetAmount int64     `json:"budget_amount"`
}

func (q *Queries) CreateDraw(ctx context.Context, arg CreateDrawParams) (Draw, error) {
	row := q.db.QueryRowContext(ctx, createDraw, arg.DrawerID, arg.ExchangeDate, arg.BudgetAmount)
	var i Draw
	err := row.Scan(
		&i.ID,
		&i.DrawerID,
		&i.ExchangeDate,
		&i.BudgetAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDraw = `-- name: DeleteDraw :exec
DELETE FROM draws WHERE id = ?
`

func (q *Queries) DeleteDraw(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDraw, id)
	return err
}

const getDraw = `-- name: GetDraw :one
SELECT id, drawer_id, exchange_date, budget_amount, status, created_at, updated_at FROM draws WHERE id = ?
`

func (q *Queries) GetDraw(ctx context.Context, id int64) (Draw, error) {
	row := q.db.QueryRowContext(ctx, getDraw, id)
	var i Draw
	err := row.Scan(
		&i.ID,
		&i.DrawerID,
		&i.ExchangeDate,
		&i.BudgetAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDrawsByDrawer = `-- name: ListDrawsByDrawer :many
SELECT id, drawer_id, exchange_date, budget_amount, status, created_at, updated_at FROM draws WHERE drawer_id = ? ORDER BY exchange_date DESC
`

func (q *Queries) ListDrawsByDrawer(ctx context.Context, drawerID int64) ([]Draw, error) {
	rows, err := q.db.QueryContext(ctx, listDrawsByDrawer, drawerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Draw
	for rows.Next() {
		var i Draw
		if err := rows.Scan(
			&i.ID,
			&i.DrawerID,
			&i.ExchangeDate,
			&i.BudgetAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCompletedDrawsByDrawer = `-- name: ListRecentCompletedDrawsByDrawer :many
SELECT id, drawer_id, exchange_date, budget_amount, status, created_at, updated_at FROM draws
WHERE drawer_id = ? AND id != ? AND status != 'draft'
ORDER BY exchange_date DESC
LIMIT ?
`

type ListRecentCompletedDrawsByDrawerParams struct {
	DrawerID int64 `json:"drawer_id"`
	ID       int64 `json:"id"`
	Limit    int64 `json:"limit"`
}

// ListRecentCompletedDrawsByDrawer returns the drawer's most recent draws
// that actually produced an assignment ('assigned' or 'notified'
// status), excluding the draw currently being run, most-recent-first,
// capped at limit. RunDraw uses this to build the history window; the
// 'draft' filter keeps an unrelated in-progress draw for the same
// drawer from ever being treated as history.
func (q *Queries) ListRecentCompletedDrawsByDrawer(ctx context.Context, arg ListRecentCompletedDrawsByDrawerParams) ([]Draw, error) {
	rows, err := q.db.QueryContext(ctx, listRecentCompletedDrawsByDrawer, arg.DrawerID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Draw
	for rows.Next() {
		var i Draw
		if err := rows.Scan(
			&i.ID,
			&i.DrawerID,
			&i.ExchangeDate,
			&i.BudgetAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDraw = `-- name: UpdateDraw :one
UPDATE draws SET exchange_date = ?, budget_amount = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, drawer_id, exchange_date, budget_amount, status, created_at, updated_at
`

type UpdateDrawParams struct {
	ExchangeDate time.Time `json:"exchange_date"`
	BudgetAmount int64     `json:"budget_amount"`
	ID           int64     `json:"id"`
}

// UpdateDraw only ever touches exchange_date/budget_amount, not status -
// that stays UpdateDrawStatus's job. The app layer is responsible for
// rejecting an update once a draw has left 'draft' status; this query has
// no WHERE status = 'draft' guard, so a caller that skips that check would
// silently succeed against an already-run draw.
func (q *Queries) UpdateDraw(ctx context.Context, arg UpdateDrawParams) (Draw, error) {
	row := q.db.QueryRowContext(ctx, updateDraw, arg.ExchangeDate, arg.BudgetAmount, arg.ID)
	var i Draw
	err := row.Scan(
		&i.ID,
		&i.DrawerID,
		&i.ExchangeDate,
		&i.BudgetAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDrawStatus = `-- name: UpdateDrawStatus :one
UPDATE draws SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, drawer_id, exchange_date, budget_amount, status, created_at, updated_at
`

type UpdateDrawStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateDrawStatus(ctx context.Context, arg UpdateDrawStatusParams) (Draw, error) {
	row := q.db.QueryRowContext(ctx, updateDrawStatus, arg.Status, arg.ID)
	var i Draw
	err := row.Scan(
		&i.ID,
		&i.DrawerID,
		&i.ExchangeDate,
		&i.BudgetAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
