// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: members.sql

package sqlc

import (
	"context"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (drawer_id, full_name, phone_number) VALUES (?, ?, ?) RETURNING id, drawer_id, full_name, phone_number, created_at, updated_at
`

type CreateMemberParams struct {
	DrawerID    int64  `json:"drawer_id"`
	FullName    string `json:"full_name"`
	PhoneNumber string `json:"phone_number"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, createMember, arg.DrawerID, arg.FullName, arg.PhoneNumber)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.DrawerID,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members WHERE id = ?
`

func (q *Queries) DeleteMember(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMember, id)
	return err
}

const getMember = `-- name: GetMember :one
SELECT id, drawer_id, full_name, phone_number, created_at, updated_at FROM members WHERE id = ?
`

func (q *Queries) GetMember(ctx context.Context, id int64) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.DrawerID,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembersByDrawer = `-- name: ListMembersByDrawer :many
SELECT id, drawer_id, full_name, phone_number, created_at, updated_at FROM members WHERE drawer_id = ? ORDER BY id
`

func (q *Queries) ListMembersByDrawer(ctx context.Context, drawerID int64) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, listMembersByDrawer, drawerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.DrawerID,
			&i.FullName,
			&i.PhoneNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersByPhoneNumber = `-- name: ListMembersByPhoneNumber :many
SELECT id, drawer_id, full_name, phone_number, created_at, updated_at FROM members WHERE phone_number = ? ORDER BY drawer_id
`

func (q *Queries) ListMembersByPhoneNumber(ctx context.Context, phoneNumber string) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, listMembersByPhoneNumber, phoneNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.DrawerID,
			&i.FullName,
			&i.PhoneNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE members SET full_name = ?, phone_number = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, drawer_id, full_name, phone_number, created_at, updated_at
`

type UpdateMemberParams struct {
	FullName    string `json:"full_name"`
	PhoneNumber string `json:"phone_number"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, updateMember, arg.FullName, arg.PhoneNumber, arg.ID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.DrawerID,
		&i.FullName,
		&i.PhoneNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
