// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: relationships.sql

package sqlc

import (
	"context"
)

const createRelationship = `-- name: CreateRelationship :one
INSERT INTO relationships (phone_number_a, phone_number_b) VALUES (?, ?) RETURNING id, phone_number_a, phone_number_b, created_at
`

type CreateRelationshipParams struct {
	PhoneNumberA string `json:"phone_number_a"`
	PhoneNumberB string `json:"phone_number_b"`
}

// CreateRelationship does not sort its two arguments. The migration's
// CHECK (phone_number_a < phone_number_b) will reject a call where
// phone_number_a is not less than phone_number_b: the caller is
// responsible for sorting the pair before calling this query.
func (q *Queries) CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (Relationship, error) {
	row := q.db.QueryRowContext(ctx, createRelationship, arg.PhoneNumberA, arg.PhoneNumberB)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.PhoneNumberA,
		&i.PhoneNumberB,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRelationship = `-- name: DeleteRelationship :exec
DELETE FROM relationships WHERE id = ?
`

func (q *Queries) DeleteRelationship(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRelationship, id)
	return err
}

const listRelationshipsForPhoneNumber = `-- name: ListRelationshipsForPhoneNumber :many
SELECT id, phone_number_a, phone_number_b, created_at FROM relationships WHERE phone_number_a = ? OR phone_number_b = ? ORDER BY id
`

type ListRelationshipsForPhoneNumberParams struct {
	PhoneNumberA string `json:"phone_number_a"`
	PhoneNumberB string `json:"phone_number_b"`
}

// ListRelationshipsForPhoneNumber takes the same phone number twice
// (PhoneNumberA and PhoneNumberB): it is not a two-number lookup. Passing
// different values, or leaving one unset, silently returns only the
// relationships where that phone number happens to be stored in the
// matching column.
func (q *Queries) ListRelationshipsForPhoneNumber(ctx context.Context, arg ListRelationshipsForPhoneNumberParams) ([]Relationship, error) {
	rows, err := q.db.QueryContext(ctx, listRelationshipsForPhoneNumber, arg.PhoneNumberA, arg.PhoneNumberB)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Relationship
	for rows.Next() {
		var i Relationship
		if err := rows.Scan(
			&i.ID,
			&i.PhoneNumberA,
			&i.PhoneNumberB,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
