// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: widgets.sql

package sqlc

import (
	"context"
)

const createWidget = `-- name: CreateWidget :one
INSERT INTO widgets (name) VALUES (?) RETURNING id, name, created_at
`

func (q *Queries) CreateWidget(ctx context.Context, name string) (Widget, error) {
	row := q.db.QueryRowContext(ctx, createWidget, name)
	var i Widget
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteWidget = `-- name: DeleteWidget :exec
DELETE FROM widgets WHERE id = ?
`

func (q *Queries) DeleteWidget(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWidget, id)
	return err
}

const getWidget = `-- name: GetWidget :one
SELECT id, name, created_at FROM widgets WHERE id = ?
`

func (q *Queries) GetWidget(ctx context.Context, id int64) (Widget, error) {
	row := q.db.QueryRowContext(ctx, getWidget, id)
	var i Widget
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listWidgets = `-- name: ListWidgets :many
SELECT id, name, created_at FROM widgets ORDER BY id
`

func (q *Queries) ListWidgets(ctx context.Context) ([]Widget, error) {
	rows, err := q.db.QueryContext(ctx, listWidgets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Widget
	for rows.Next() {
		var i Widget
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWidget = `-- name: UpdateWidget :one
UPDATE widgets SET name = ? WHERE id = ? RETURNING id, name, created_at
`

type UpdateWidgetParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateWidget(ctx context.Context, arg UpdateWidgetParams) (Widget, error) {
	row := q.db.QueryRowContext(ctx, updateWidget, arg.Name, arg.ID)
	var i Widget
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
