// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: wishlist_items.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createWishlistItem = `-- name: CreateWishlistItem :one
INSERT INTO wishlist_items (phone_number, item_name, size, url) VALUES (?, ?, ?, ?) RETURNING id, phone_number, item_name, size, url, created_at, updated_at
`

type CreateWishlistItemParams struct {
	PhoneNumber string         `json:"phone_number"`
	ItemName    string         `json:"item_name"`
	Size        sql.NullString `json:"size"`
	Url         sql.NullString `json:"url"`
}

func (q *Queries) CreateWishlistItem(ctx context.Context, arg CreateWishlistItemParams) (WishlistItem, error) {
	row := q.db.QueryRowContext(ctx, createWishlistItem,
		arg.PhoneNumber,
		arg.ItemName,
		arg.Size,
		arg.Url,
	)
	var i WishlistItem
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.ItemName,
		&i.Size,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWishlistItem = `-- name: DeleteWishlistItem :exec
DELETE FROM wishlist_items WHERE id = ?
`

func (q *Queries) DeleteWishlistItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWishlistItem, id)
	return err
}

const getWishlistItem = `-- name: GetWishlistItem :one
SELECT id, phone_number, item_name, size, url, created_at, updated_at FROM wishlist_items WHERE id = ?
`

func (q *Queries) GetWishlistItem(ctx context.Context, id int64) (WishlistItem, error) {
	row := q.db.QueryRowContext(ctx, getWishlistItem, id)
	var i WishlistItem
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.ItemName,
		&i.Size,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWishlistItemsByPhoneNumber = `-- name: ListWishlistItemsByPhoneNumber :many
SELECT id, phone_number, item_name, size, url, created_at, updated_at FROM wishlist_items WHERE phone_number = ? ORDER BY id
`

func (q *Queries) ListWishlistItemsByPhoneNumber(ctx context.Context, phoneNumber string) ([]WishlistItem, error) {
	rows, err := q.db.QueryContext(ctx, listWishlistItemsByPhoneNumber, phoneNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WishlistItem
	for rows.Next() {
		var i WishlistItem
		if err := rows.Scan(
			&i.ID,
			&i.PhoneNumber,
			&i.ItemName,
			&i.Size,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWishlistItem = `-- name: UpdateWishlistItem :one
UPDATE wishlist_items SET item_name = ?, size = ?, url = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, phone_number, item_name, size, url, created_at, updated_at
`

type UpdateWishlistItemParams struct {
	ItemName string         `json:"item_name"`
	Size     sql.NullString `json:"size"`
	Url      sql.NullString `json:"url"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateWishlistItem(ctx context.Context, arg UpdateWishlistItemParams) (WishlistItem, error) {
	row := q.db.QueryRowContext(ctx, updateWishlistItem,
		arg.ItemName,
		arg.Size,
		arg.Url,
		arg.ID,
	)
	var i WishlistItem
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.ItemName,
		&i.Size,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
